### ISSUE TITLE
masternode automatically goes to MISSING!

### ISSUE THREAD

**Issue by kiahmed** [wagerr/wagerr#21]
### Describe the issue
I had MN up and running with staking icon on couple nights ago. Yesterday my server restarted and since then when I start the MN it remains ENABLED on for several hours then falls back to MISSING on its own and also the staking would never turn on again even with unlocked wallet and checked option.
Also the time remains 0:00 and sometimes goes to negative ..whats that mean?

#### If so, please list the steps to reproduce below:
1. start MN
2.wait for hours
3. see its missing

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Screenshots.

![capture](https://user-images.githubusercontent.com/28849607/36693672-0e09c28a-1b0a-11e8-8bd1-e3888f0557a4.PNG)

### What version of Wagerr Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS: win10
- CPU: 4.2 ghz
- RAM: 32 gb
- Disk size: 200 gb
- Disk Type (HD/SDD): ssd

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by WagerrTor** [comment]
Hello,

there are many guides on internet where you can look up all different variations which can be used with a masternode.

if you use _masternode.conf_ (multi mode) instead of single mode, **you need to ensure that you run a script restarting your masternodes in some period of time**. **All masternode coins have this issue** and in most cases _users are told to use single mode_ as it requires some additional steps to ensure that your masternodes run.

In single mode, please add `logtimestamps=1`then time will show properly too. Once again, _if you run masternodes in multi mode your time will not show correctly_.

- To run masternode in single mode please ensure to have these settings in your config:

```
    masternode=1
    externalip=YourExternalIPAddress
    masternodeaddr=YourExternalIPAddress:55002
```

- to switch from single/multinode use masternode, where 1 = single mode and 0 = multi mode
    - your port over that ip must be reachable. You need to open and forward this port properly in your network or VPN. 
        
        To check if your port is open, there are several ways, probably the easiest is to telnet and if you receive any answer (some cryptic answer), then it means your port is open

```
            telnet YourExternalIP 55002
```

- Sample config part for **masternode single mode** (ensure that your masternodes use **always port 55002**):

```
        rpcuser=yourpcuser
        rpcpassword=SOMELonGgoodpASSWORd
        logtimestamps=1
        masternode=1
        externalip=YourExternalIPAddress
        masternodeaddr=YourExternalIPAddress:55002
        masternodeprivkey=7xxxMasternodePrivateYouGetWith-masternodegenkeyxxN
```

- Sample config part for **masternode multi mode** (ensure that your masternodes use **always port 55002**):

```
        rpcuser=yourpcuser
        rpcpassword=SOMELonGgoodpASSWORd
        masternode=0
        externalip=YourExternalIPAddress
```

- Sample config part for **masternode single mode** using **bind and disabled zeromint** (ensure that your masternodes use **always port 55002**):

```
        server=1
        listen=0
        daemon=1
        zeromint=0
        enablezeromint=0
        logtimestamps=1
        rpcuser=yourpcuser
        rpcpassword=SOMELonGgoodpASSWORd
        masternode=1
        externalip=YourExternalIPAddress
        bind=YourExternalIPAddress
        masternodeaddr=YourExternalIPAddress:55002
        masternodeprivkey=7xxxMasternodePrivateYouGetWith-masternodegenkeyxxN
```

- Sample config part for **masternode single mode** using **listen and disabled zeromint** (ensure that your masternodes use **always port 55002**):

```
        server=1
        listen=1
        daemon=1
        zeromint=0
        enablezeromint=0
        logtimestamps=1
        rpcuser=yourpcuser
        rpcpassword=SOMELonGgoodpASSWORd
        masternode=1
        externalip=YourExternalIPAddress
        masternodeaddr=YourExternalIPAddress:55002
        masternodeprivkey=7xxxMasternodePrivateYouGetWith-masternodegenkeyxxN
```

- Sample config part for **masternode single mode** using **bind and enabled zeromint** (ensure that your masternodes use **always port 55002**):

```
        server=1
        listen=0
        daemon=1
        zeromint=1
        enablezeromint=1
        logtimestamps=1
        rpcuser=yourpcuser
        rpcpassword=SOMELonGgoodpASSWORd
        masternode=1
        externalip=YourExternalIPAddress
        bind=YourExternalIPAddress
        masternodeaddr=YourExternalIPAddress:55002
        masternodeprivkey=7xxxMasternodePrivateYouGetWith-masternodegenkeyxxN
```

- Sample config part for **masternode single mode** using **listen and enabled zeromint** (ensure that your masternodes use **always port 55002**):

```
        server=1
        listen=1
        daemon=1
        zeromint=1
        enablezeromint=1
        logtimestamps=1
        rpcuser=yourpcuser
        rpcpassword=SOMELonGgoodpASSWORd
        masternode=1
        externalip=YourExternalIPAddress
        masternodeaddr=YourExternalIPAddress:55002
        masternodeprivkey=7xxxMasternodePrivateYouGetWith-masternodegenkeyxxN
```

For masternode.conf, please look in your folder up, it is very well described there.

  - If you use multiple masternodes on same device/server, you can run them all, you need only to specify different ports (port/rpcport) in your config.

    - You must use same masternode port in your masternode.conf and in `masternodeaddr=YourExternalIPAddress:55002`.
    - You can use mixed mode with staking, masternodes staking and zeromint in one instance. We will write up guides about this part.
    - For cold start you can use 127.0.0.x ip addresses, please look up commented part in autocreated masternode.conf in your data directory.

**Comment by kiahmed** [comment]
all the configs are done right. I even ran under a new mn key. It still keeps falling back to MISSING. I am not sure then how other people kept running and getting rewards then?

**Comment by WagerrTor** [comment]
can you post your configs?
(_please make sure that you removed private keys, username and password/s from your config before posting, please double check when you do so, it happened already in past that people uploaded their private keys or username/password when they shared their configs in public_)

**Comment by WagerrTor** [comment]
I assume this is resolved and will close it, feel free to reopen if issue persists
